### PR TITLE
Chat interface updates - new flags for multi-line input, model choice selection, updated paragraph wrapping for output and option flag to disable, and minor bugfixes

### PR DESCRIPTION
**Pull request by PeteHemery**
Following on the inspiration to share back to the community from PR 227, I offer these improvements.
The commit messages should have most of the info there. 
I did modify/comment out this line
text = resp_answer #click.wrap_text(resp_answer, width=78, preserve_paragraphs=True)
since the formatted text returned does look right when it prints mardown code.

Let me know what you think.

### CODE REVIEW

**Comment by PeteHemery** [comment]
Ah, also added a mini timeout feature, for when requests occasionally go bad. Probably should change the commit message to reflect that. Will wait for feedback

**Comment by PeteHemery** [comment]
split commits up into manageable chunks. hope some are good for cherry picking

**Comment by PeteHemery** [comment]
always with the "just one more thing" with git ;)
played with this a lot today.
I've also been making some improvements to the save chat functionality too. being able to name saved chats as you start them, and allowing branches with reworking from a certain point. need to save the chat_vdqs along the way. open for a discussion, if it'd be of any interest?

**Comment by deedy5** [comment]
The code is overcomplicated.

**Comment by PeteHemery** [comment]
@deedy5 thank you for your feedback. I'm curious as to which bit you found over complicated. I spent a lot of time triying to split things into minimal change sets in the individual commits.
There are some bug fixes in there. Would you like me to open a separate PR with just those?

**Pull request closed without merging**
