### PR TITLE
Add new chat functionality

### PR DESCRIPTION
**Pull request by mplawner**
Added new features to chat:
-m/--model model selection
-t/--text input text
without -t/--text reads from standard input.
E.g.
echo "Tell me a joke." | ddgs chat -m "gpt-3.5"

### CODE REVIEW

**Comment by deedy5** [comment]
Thanks :+1: , but I don't think the chat will be used by anyone in that way.

**Comment by PeteHemery** [comment]
@deedy5 I actually made a similar modification to allow multiline input usage. Will open a seperate PR

**Comment by deedy5** [comment]
multiline input usage?

**Comment by PeteHemery** [comment]
[PR 230](https://github.com/deedy5/duckduckgo_search/pull/230)

**Pull request closed without merging**
