### PR TITLE
[simplify]: remove AsyncDDGS, remove `answers`, `maps`, `suggestions`, `translate`; [text]: remove multithreading

### PR DESCRIPTION
**Pull request by deedy5**
1) Remove AsyncDDGS
2) Remove defs `answers`, `maps`, `suggestions`, `translate`
3) DDGS.text: remove multithreading, 
4) Add delay between requests

### CODE REVIEW

**Comment by Shulyaka** [comment]
Oh no, not the maps!..

**Comment by Kludex** [comment]
Why was the async interface removed?

**Comment by deedy5** [comment]
To simplify code maintenance. 
You can just use  [asyncio.loop.run_in_executor](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor):
```python
import asyncio
from duckduckgo_search import DDGS

def search(word):
    results = DDGS().text(word)
    return results

async def asearch(word):
    loop = asyncio.get_running_loop()
    results = await loop.run_in_executor(None, search, word)
    return results

async def main():
    words = ["sun", "earth", "moon"]
    tasks = [asearch(w) for w in words]
    results = await asyncio.gather(*tasks)
    print(results)

if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by deedy5** [comment]
Have to change clients for requests. Each client has its own interface, its own peculiarities of implementation, its own emerging bugs (especially in asynchronous implementation). At some point it became easier to focus on synchronous mode. Those who need asynchronous can wrap DDGS using `asyncio.run_in_executor`

**Pull request merged**
