### PR TITLE
add llama-3 and mixtral model for ai chat

### PR DESCRIPTION
**Pull request by hjlarry**
Hi，the duckduckgo now support  [two more models](https://duckduckgo.com/duckduckgo-help-pages/aichat/chat-models/)

I added them and tested locally.

### CODE REVIEW

**Comment by PeteHemery** [comment]
You might want to add this too
```diff
diff --git a/duckduckgo_search/cli.py b/duckduckgo_search/cli.py
index deccd8c..1b609f6 100644
--- a/duckduckgo_search/cli.py
+++ b/duckduckgo_search/cli.py
@@ -137,7 +137,7 @@ def version():
 def chat(save, proxy):
     """CLI function to perform an interactive AI chat using DuckDuckGo API."""
     cache_file = "ddgs_chat_conversation.json"
-    models = ["gpt-3.5", "claude-3-haiku"]
+    models = ["gpt-3.5", "claude-3-haiku", "llama-3", "mixtral"]
     client = DDGS(proxy=proxy)
 
     print("DuckDuckGo AI chat. Available models:")
```

**Comment by hjlarry** [comment]
> You might want to add this too
> 
> ```diff
> diff --git a/duckduckgo_search/cli.py b/duckduckgo_search/cli.py
> index deccd8c..1b609f6 100644
> --- a/duckduckgo_search/cli.py
> +++ b/duckduckgo_search/cli.py
> @@ -137,7 +137,7 @@ def version():
>  def chat(save, proxy):
>      """CLI function to perform an interactive AI chat using DuckDuckGo API."""
>      cache_file = "ddgs_chat_conversation.json"
> -    models = ["gpt-3.5", "claude-3-haiku"]
> +    models = ["gpt-3.5", "claude-3-haiku", "llama-3", "mixtral"]
>      client = DDGS(proxy=proxy)
>  
>      print("DuckDuckGo AI chat. Available models:")
> ```

yes, I forgot to add it, thanks!

**Review by deedy5 — CHANGES_REQUESTED** [review]
There will probably be some other models appearing there, so it is advisable to name them more specifically: "llama-3-70b", "mixtral-8x7b"

**Comment by hjlarry** [comment]
> There will probably be some other models appearing there, so it is advisable to name them more specifically: "llama-3-70b", "mixtral-8x7b"

Ok, I have already renamed them, please review it.

**Review by deedy5 — APPROVED** [review]

**Comment by deedy5** [comment]
Changes reverted, not working. Need to add tests for specific models as well.

**Pull request merged**
